<a href="https://colab.research.google.com/github/SusanGicheha/AI-ML-Group-Task/blob/main/ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np 

In [ ]:
from numpy import array
from sklearn.preprocessing import Normalizer
from keras.activations import sigmoid
from keras.losses import mse 
from numpy.random import uniform,normal

In [ ]:
batch_size=6

In [ ]:
data_dict={'Day 1': [30,40,50,20,15,60], 'Day 2': [40,50,20,15,60,70], 
           'Day 3':[50,20,15,60,70,50], 'Target':[20,15,60,70,50,40]}

In [ ]:
data=pd.DataFrame(data_dict)

In [ ]:
data

Day 1  Day 2  Day 3  Target
0     30     40     50      20
1     40     50     20      15
2     50     20     15      60
3     20     15     60      70
4     15     60     70      50
5     60     70     50      40

In [ ]:
X=data.drop('Target',axis=1)
y=data['Target']

In [ ]:
X_trans=Normalizer(norm='max').fit_transform(X)

In [ ]:
np.reshape(array(y),(1,-1))
array([[20,15,60,70,50,40]])

array([[20, 15, 60, 70, 50, 40]])

In [ ]:
y=Normalizer(norm='max').fit_transform(np.reshape(array(y),(1,-1)))

In [ ]:
y

array([[0.28571429, 0.21428571, 0.85714286, 1.        , 0.71428571,
        0.57142857]])

In [ ]:
X_trans

array([[0.6       , 0.8       , 1.        ],
       [0.8       , 1.        , 0.4       ],
       [1.        , 0.4       , 0.3       ],
       [0.33333333, 0.25      , 1.        ],
       [0.21428571, 0.85714286, 1.        ],
       [0.85714286, 1.        , 0.71428571]])

ANN Model from Scratch

In [ ]:
X_trans.shape

(6, 3)

In [ ]:
#form weight matrixes
#weight_1=array([[.2,.1],[.3,.1],[.2,.1]])
#weight_2=array([[.5],[.1]])

In [ ]:
 weight_1=uniform(-1,1,(3,2))
weight_2=uniform(-1,1,(2,1))

In [ ]:
weight_1

array([[ 0.41989292,  0.6217181 ],
       [-0.08271472, -0.64648719],
       [ 0.97382056,  0.71354281]])

In [ ]:
weight_2

array([[-0.28225475],
       [ 0.68687119]])

In [ ]:
X=X_trans

In [ ]:
X[0:batch_size]

array([[0.6       , 0.8       , 1.        ],
       [0.8       , 1.        , 0.4       ],
       [1.        , 0.4       , 0.3       ],
       [0.33333333, 0.25      , 1.        ],
       [0.21428571, 0.85714286, 1.        ],
       [0.85714286, 1.        , 0.71428571]])

In [ ]:
X[0:batch_size].shape #shape of matrix

(6, 3)

In [ ]:
output_1=X[0:batch_size]@weight_1 #multiply matrix

In [ ]:
output_1 

array([[1.15958453, 0.56938392],
       [0.64272784, 0.13630442],
       [0.6789532 , 0.57718607],
       [1.09310618, 0.75916038],
       [0.99289928, 0.29263624],
       [0.97277961, 0.39608748]])

In [ ]:
act_output_1=sigmoid(output_1).numpy() #activation fn
act_output_1

array([[0.76125721, 0.63862101],
       [0.65536983, 0.53402344],
       [0.66350502, 0.64041966],
       [0.74896618, 0.68117142],
       [0.7296602 , 0.57264141],
       [0.72567319, 0.59774727]])

In [ ]:
act_output_1.shape

(6, 2)

In [ ]:
actual_output = act_output_1.T

In [ ]:
actual_output.shape

(2, 6)

In [ ]:
final_output=act_output_1@weight_2
final_output #output at k day 0 to day 5

array([[0.22378191],
       [0.18182407],
       [0.25260838],
       [0.25647776],
       [0.18738083],
       [0.20575068]])

In [ ]:
final_output.shape

(6, 1)

In [ ]:
y_true=y[0][0:batch_size] # y = target
y_pred=final_output.T[0] #t = transpose

In [ ]:
y_true #true target values

array([0.28571429, 0.21428571, 0.85714286, 1.        , 0.71428571,
       0.57142857])

In [ ]:
y_pred # predicted target

array([0.22378191, 0.18182407, 0.25260838, 0.25647776, 0.18738083,
       0.20575068])

above was foward propagation

compute mean squared error

In [ ]:
error_K = mse(y_true,y_pred).numpy()
error_K

0.22242095272121024

Back propagation

In [ ]:
#calculate error (k) = 𝒚-hat(𝒚) ∗ hat(𝒚)(𝟏-hat(y))
error_k = y_true - y_pred * (y_pred * (1 - y_pred ))
error_k

array([0.24684257, 0.18723682, 0.80945106, 0.95109048, 0.68575338,
       0.53780534])

In [ ]:
error_j = error_k * weight_2[1]  * (actual_output[1]*(1-actual_output[1])) 
error_j

array([0.03912924, 0.03200302, 0.12803435, 0.14187661, 0.11527057,
       0.08882128])

In [ ]:
error_i = error_k * weight_2[0] * (actual_output[0]*(1-actual_output[0])) 
error_i

array([-0.0126626 , -0.01193637, -0.05100992, -0.05047282, -0.03818035,
       -0.0302187 ])

Delta rule

In [ ]:
epochs = 100
for ep in range(100):
 learning_rate = 0.3
new_jk = weight_2[1] + ( learning_rate * error_k * y_pred )

new_ik = weight_2[0] + ( learning_rate * error_k * y_pred )
